# @format

version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
  php-app:
    image: php:apache
    volumes:
      - ./php:/var/www/html
    ports:
      - '3000:80'
    depends_on:
      - mysql
  node-app:
    image: node
    working_dir: /usr/src/app
    volumes:
      - ./nodejs:/usr/src/app
    ports:
      - '3001:3001'
    command: npm run start
  golang-app:
    image: golang
    working_dir: /go/src/app
    ports:
      - '3002:3002'
    volumes:
      - ./go:/go/src/app
    command: go run .
